
#ifndef __PRESETS

#define __PRESETS

class presets {

   static constexpr char maps[10][25][51] = { 
                                    // nothing
                                    { 
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  "
                                    },
                                    // sparse
                                    { 
                                       "  x     x   x     x      x                        ",
                                       "                       x       x    x          x  ",
                                       "    x   x      x     x      x            x        ",
                                       "            x     x                 x             ",
                                       "       x               x       x        x   x     ",
                                       "    x       x    x       x                      x ",
                                       "              x      x              x       x     ",
                                       "    x    x               x    x         x         ",
                                       "                 x                                ",
                                       "      x   x          x     x     x            x   ",
                                       "              x                      x    x       ",
                                       "      x   x          x  x     x  x            x   ",
                                       "                x          x              x       ",
                                       "          x         x          x   x  x           ",
                                       "    x                     x               x   x   ",
                                       "         x    x        x         x                ",
                                       "                  x          x       x       x    ",
                                       "    x   x   x            x         x      x       ",
                                       "                    x                 x           ",
                                       "              x              x   x            x   ",
                                       "    x    x       x   x    x                x      ",
                                       "                                   x  x        x  ",
                                       "     x        x    x    x    x  x                 ",
                                       "          x                             x   x     ",
                                       "                                                  "
                                    },
                                    // box
                                    { 
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                     xxxxxxx                      ",
                                       "                     x     x                      ",
                                       "                     x     x                      ",
                                       "                     xxxxxxx                      ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  "
                                    },
                                    // classic
                                    { 
                                       "                                                  ",
                                       "           xxxxxxxxxxxxxxxxxxxxxx   xxxxxxxx      ",
                                       "           x                    x   x      x      ",
                                       "           x                    x   x      x      ",
                                       "           x       xxxxx        x   x      x      ",
                                       "           x       x   x        x   x      x      ",
                                       "           x       x   x        x   x      x      ",
                                       "           x       x   x        x   x      x      ",
                                       "           x       x   x        x   x      x      ",
                                       "           x       x   x        x   x      x      ",
                                       "           x       x   x        x   x      x      ",
                                       "           x       x   x        x   x      x      ",
                                       "           x       x   x        x   x      x      ",
                                       "           x       x   x        x   x      x      ",
                                       "           x       x   x        x   x      x      ",
                                       "           x       x   x        x   x      x      ",
                                       "           x       x   x        xxxxx      x      ",
                                       "           x       x   x                   x      ",
                                       "           x       x   x                   x      ",
                                       "           xxxxxxxxx   xxxxxxxxxxxxxxxxxxxxx      ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  ",
                                       "                                                  "
                                    },
                                    // rooms
                                    { 
                                       "         xxxxxxxxxxxxxxxxxxxxxxxxxxxx             ",
                                       "         x                          x             ",
                                       "         x xxxxxxxxxxxxxxxxxxxxxxxx x             ",
                                       "         x x                      x x             ",
                                       " xxxxx   x x   xxxxx              x x             ",
                                       " x   x   x x   x   x              x x             ",
                                       " x   xxxxx xxxxx   xxxxxxx      xxx xxx           ",
                                       " x                       x      x     x           ",
                                       " x   xxxxx xxxxx   xxxxx x      x     x           ",
                                       " x   x   x x   x   x   x x      xxx xxx           ",
                                       " xxxxx   x x   xxxxx xxx xxx      x x             ",
                                       "         x x         x     x      x x     xxxxxxx ",
                                       "         x x         x     x    xxx xxx   x     x ",
                                       "   xxxxxxx x   xxxxx xxx xxx    x     x   x     x ",
                                       "   x       x   x   x   x x      x     x   xxx xxx ",
                                       "   x xxxxxxx   x   xxxxx x      xxx xxx     x x   ",
                                       "   x x         x         x        x x       x x   ",
                                       "   x x         x   xxxxx x        x xxxxxxxxx x   ",
                                       "   x x         x   x   x x        x           x   ",
                                       " xxx xxx       xxxxx xxx xxx      xxxxxxxxxxxxx   ",
                                       " x     x             x     x                      ",
                                       " x     x             x     x                      ",
                                       " xxxxxxx             xxxxxxx                      ",
                                       "                                                  ",
                                       "                                                  ",
                                    },
                                    // maze 1
                                    { 
                                       "     xxxxxxxxxxxx                        xxxxxxxxx",
                                       "            xxxxx xxxxxxxxxxxxxxxxxxxxxx xxxxxxxxx",
                                       "     xxxxxx xxxxx xxxx           xxxxxxx xxxxxxxxx",
                                       "xxxxxxxxxxx xxxxx xxxx xxxxxxxxx xxxxxxx xxxxxxxxx",
                                       "xxxxxxxxxxx xxxxx xxxx xxxxxxxxx xxxxxxx xxxxxxxxx",
                                       "xxxxxxxxxxx xxxxx xxxx        xx xxxxxxx xxxxxxxxx",
                                       "xxxxxxxxxxx xxxxx xxxxxxxxxxx xx xxxxxxx xxxxxxxxx",
                                       "xxxxxxxxxxx xxxxx xxxxxxxxxxx xx xxxxxxx xxxxxxxxx",
                                       "xxxx        xxxxx             xx xxxxxxx xxxxxxxxx",
                                       "xxxx xxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxx xxxxxxxxx",
                                       "xxxx xxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxx xxxxxxxxx",
                                       "xxxx xxxxxxxxxxxx        xxxxxxx xxxxxxx xxxxxxxxx",
                                       "xxxx xxxxxxxxxxxx xxxxxx xxxxxxx xxxxxxx xxxxxxxxx",
                                       "xxxx xxxxxxxx     xxxxxx xxxxxxx xxxxxxx xxxxxxxxx",
                                       "xxxx xxxxxxxx xxxxxxxxxx xxxxxxx xxxxxxx xxxxxxxxx",
                                       "xxxx xxxxx    xxxxx      xxxxxxx xxxxxxx xxxxxxxxx",
                                       "xxxx xxxxx xxxxxxxx xxxxxxxxxxxx xxxxxxx xxxxxxxxx",
                                       "xxxx xxxxx xxxxxxxx xxxxxxxxxxxx xxxxxxx xxxxxxxxx",
                                       "xxxx       xxxxxxxx xxxxxxxxxxxx xxxxxxx xxxxxxxxx",
                                       "xxxxxxxxxxxxxxxxxxx xxxxxxxxxxxx xxxxxxx xxxxxxxxx",
                                       "xxxxxxxxxxxxxxxxxxx xxxxxxxxxxxx xxxxxxx xxxxxxxxx",
                                       "xxxxxxxxxxxxxxxxxxx xxxxxxxxxxxx xxxxxxx xxxxxxxxx",
                                       "xxxxxxxxxxxxxxxxxxx              xxxxxxx xxxx     ",
                                       "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          ",
                                       "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
                                    },
                                    // maze 2
                                    { 
                                       "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                                       "xx        xxx           xxxxxxxxxxxxxxx      xxxxx",
                                       "xx xxxxxx  xx xxxxxxxxx                      xxxxx",
                                       "xx xxxxxxx xx xx        xxxxxxx xxxxxxx      xxxxx",
                                       "xx       xxxx xx xxxxxxxxxxxxxx xxxx xxxx xxxxxxxx",
                                       "xxxxxxxx x    xx          xxxxx xxxx xxxx xx    xx",
                                       "xxxxxxxx x xxxxxxxxxxxxxx xxxxx      xxxx xx xx xx",
                                       "xx       x xxx        xxx xxxxxxxxxxxxxxx xx xx xx",
                                       "xx xxxxxxx xxx xxxxxx xxx    xxxxx    xxx xx xx xx",
                                       "xx xxx     xxx xxxxxx xxxxxx xxxxx xx xxx xx xx xx",
                                       "xx xxx xxxxxxx xxxxx  xxxxxx xxxxx xx xxx    xx xx",
                                       "xx xxx xxx     xxxxx xxx     xxxxx xx xxxxxxxxx xx",
                                       "xx     xxx xxxxxxxxx xxx xxxxxxxxx xx xxxxx     xx",
                                       "xx xxxxxxx xxxxxxxxx xxx xxxxxxxxx xx xxxxx xxxxxx",
                                       "xx x    xx xxxxxxxxx xxx xxxxxxxxx xx xxxxx    xxx",
                                       "xx x xx xx        xx xxx xx        xx     xxxx xxx",
                                       "xx x xx xxxxxxxxx xx xxx xx xxxxxxxxxxxxx   xx xxx",
                                       "xx x xx         x x  xxx  x x           xxx xx xxx",
                                       "xx x xxxxxxxxxx x x xxxxx x x xxxxxxxxx xxx xx xxx",
                                       "xx x         xx x x       x x xxxxxxxxx xxx xx xxx",
                                       "xxxxxxxxxxxx xx x xxxxxxxxx x xxxxxxxxx xxx xx   x",
                                       "        xxxx xx x           x xxxxxxxxx xxx xxxxxx",
                                       "             xx xxxxxxxxxxxxx xxxxxxxxx xxx xxx  x",
                                       "        xxxxxxx               xxxxxxxxx         xx",
                                       "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                                    },
                                    // spiral
                                    { 
                                       "           x                       x              ",
                                       "         x x xxxxxxxxxxxxxxxxxxxxx x x x          ",
                                       "         x x x                   x x x x          ",
                                       "         x x x xxxxxxxxxxxxxxxxx x x x x          ",
                                       "         x x x x               x x x x x          ",
                                       "         x x x x xxxxxxxxxxxxx x x x x x          ",
                                       "         x x x x x           x x x x x x          ",
                                       "         x x x x x xxxxxxxxx x x x x x x          ",
                                       "         x x x x x x       x x x x x x x          ",
                                       "         x x x x x x xxxxx x x x x x x x          ",
                                       "         x x x x x x x     x x x x x x x          ",
                                       "         x x x x x x x     x x x x x x x          ",
                                       "         x x x x x x xxxxxxx x x x x x x          ",
                                       "         x x x x x x         x x x x x x          ",
                                       "         x x x x x xxxxxxxxxxx x x x x x          ",
                                       "         x x x x x             x x x x x          ",
                                       "         x x x x xxxxxxxxxxxxxxx x x x x          ",
                                       "         x x x x                 x x x x          ",
                                       "         x x x xxxxxxxxxxxxxxxxxxx x x x          ",
                                       "         x x x                     x x x          ",
                                       "         x x xxxxxxxxxxxxxxxxxxxxxxx x x          ",
                                       "         x x                         x x          ",
                                       "         x xxxxxxxxxxxxxxxxxxxxxxxxxxx x          ",
                                       "         x                             x          ",
                                       "         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          "
                                    },
                                    // corner_spiral
                                    { 
                                       "     x   x   x   x   x   x   x   x   x   x   x    ",
                                       "xxx  x x x x x x x x x x x x x x x x x x x x x x  ",
                                       "     x x x x x x x x x x x x x x x x x x x x x x  ",
                                       " xxxxx x x x x x x x x x x x x x x x x x x x x x  ",
                                       "       x x x x x x x x x x x x x x x x x x x x x  ",
                                       "xxxxxxxx x x x x x x x x x x x x x x x x x x x xxx",
                                       "         x x x x x x x x x x x x x x x x x x x    ",
                                       " xxxxxxxxx x x x x x x x x x x x x x x x x x xxxx ",
                                       "           x x x x x x x x x x x x x x x x x      ",
                                       "xxxxxxxxxxxx x x x x x x x x x x x x x x x xxxxxxx",
                                       "             x x x x x x x x x x x x x x x        ",
                                       " xxxxxxxxxxxxx x x x x x x x x x x x x x xxxxxxxx ",
                                       "               x x x x x x x x x x x x x          ",
                                       "xxxxxxxxxxxxxxxx x x x x x x x x x x x xxxxxxxxxxx",
                                       "                 x x x x x x x x x x x            ",
                                       " xxxxxxxxxxxxxxxxx x x x x x x x x x xxxxxxxxxxxx ",
                                       "                   x x x x x x x x x              ",
                                       "xxxxxxxxxxxxxxxxxxxx x x x x x x x xxxxxxxxxxxxxxx",
                                       "                     x x x x x x x                ",
                                       " xxxxxxxxxxxxxxxxxxxxx x x x x x xxxxxxxxxxxxxxxx ",
                                       "                       x x x x x                  ",
                                       "xxxxxxxxxxxxxxxxxxxxxxxx x x x xxxxxxxxxxxxxxxxxxx",
                                       "                         x x x                    ",
                                       " xxxxxxxxxxxxxxxxxxxxxxxxx x xxxxxxxxxxxxxxxxxxxx ",
                                       "                           x                      "
                                    },
                                    // office
                                    { 
                                       "xxxxxxxxxxxxxxxxxx  x        x  xxxxxxxxxxxxxxxxxx",
                                       "x    x    x      x  x        x  x      x    x    x",
                                       "xxxx xxxx xxxxxx xxxx        xxxx xxxxxx xxxx xxxx",
                                       "                                                  ",
                                       "xxxxxxxxxxxxxxxxxx  x   xx   x  xxxxxxxxxxxxxxxxxx",
                                       "x    x    x      x  x   xx   x  x      x    x    x",
                                       "xxxx xxxx xxxxxx xxxx   xx   xxxx xxxxxx xxxx xxxx",
                                       "                                                  ",
                                       "xxxxxxxxxxxxxxxxxx  x   xx   x  xxxxxxxxxxxxxxxxxx",
                                       "x    x    x      x  x   xx   x  x      x    x    x",
                                       "xxxx xxxx xxxxxx xxxx   xx   xxxx xxxxxx xxxx xxxx",
                                       "                                                  ",
                                       "xxxxxxxxxxxxxxxxxx  x   xx   x  xxxxxxxxxxxxxxxxxx",
                                       "x    x    x      x  x   xx   x  x      x    x    x",
                                       "xxxx xxxx xxxxxx xxxx   xx   xxxx xxxxxx xxxx xxxx",
                                       "                                                  ",
                                       "xxxxxxxxxxxxxxxxxx  x   xx   x  xxxxxxxxxxxxxxxxxx",
                                       "x    x    x      x  x   xx   x  x      x    x    x",
                                       "xxxx xxxx xxxxxx xxxx   xx   xxxx xxxxxx xxxx xxxx",
                                       "                                                  ",
                                       "xxxxxxxxxxxxxxxxxx  x   xx   x  xxxxxxxxxxxxxxxxxx",
                                       "x    x    x      x  x   xx   x  x      x    x    x",
                                       "xxxx xxxx xxxxxx xxxx   xx   xxxx xxxxxx xxxx xxxx",
                                       "                                                  ",
                                       "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                                    }
                                 };
public:

   static void load_map(int ** real, int num) {
      for (int i = 0; i < 50; ++i) { 
         for (int j = 0; j < 25; ++j) {
            int val = (maps[num][j][i] == ' ' ? 0 : 1);
            for (int k = 0; k < 4; ++k)
               for (int l = 0; l < 4; ++l)
                  real[i*4+k][j*4+l] = val;
         }
      }
   }
};

#endif
